# Steps executed by Copilot coding agent to prepare the ephemeral environment.
# Purpose: pre-install dependencies for Home Assistant custom component development.

steps:
  - name: Setup Python and virtual environment
    run: |
      python -m venv .venv
      source .venv/bin/activate
      pip install --upgrade pip

  - name: Install Home Assistant for validation
    run: |
      # Install Home Assistant with validation tools
      pip install homeassistant || echo "Home Assistant installation optional"

  - name: Install code quality tools
    run: |
      # Install formatters and linters
      pip install black flake8 pylint || true

  - name: Verify integration structure
    run: |
      # Check that the integration structure is valid
      ls -la custom_components/torque_obd/
      cat custom_components/torque_obd/manifest.json
